export const locations = {
  home: "/",
  aboutUs: "/about",
  products: "/products",
  product: "/products/:slug",
  markets: "/markets",
  market: "/markets/:slug",
  technologies: "/technologies",
  // technology: "/technologies/:slug",
  sucessfulCases: "/sucessful-case",
  sucessfulCase: "/sucessful-case/:id",
  download: "/download",
  contact: "/contact",
};

export const labels = {
  home: "/",
  aboutUs: "/about",
  aboutGlobal: "/about/global",
  products: "/products",
  product: "/products/:slug",
  markets: "/markets",
  market: "/markets/:slug",
  technologies: "/technology",
  technology: "/technology/:slug",
  sucessfulCases: "/sucessful-case",
  sucessfulCase: "/sucessful-case/:id",
  download: "/download",
  contact: "/contact",
  contactGlobal: "/contact/global",
};
